{% set name = "fortls" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fortls-{{ version }}.tar.gz
  sha256: 4ec963d29977b57b7ce470986aba3ba26f40d08d96e358bb63f19c9a23f8a930

build:
  skip: true  # [py<37]
  entry_points:
    - fortls = fortls.__init__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - importlib-metadata  # [py<38]
    - python
    - typing-extensions  # [py<38]
    - json5
    - packaging

test:
  imports:
    - fortls
  commands:
    - pip check
    - fortls --help
  requires:
    - pip

about:
  home: https://github.com/fortran-lang/fortls
  summary: fortls - Fortran Language Server
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gnikit
