{% set name = "fortls" %}
{% set version = "2.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fortls-{{ version }}.tar.gz
  sha256: 32ee292c3602a2f1951675fc462105eabb16281c7fc8ee5c5c597645f73f0f80

build:
  skip: true  # [py<37]
  entry_points:
    - fortls = fortls.__init__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - importlib-metadata  # [py<38]
    - python
    - typing-extensions  # [py<38]

test:
  imports:
    - fortls
  commands:
    - pip check
    - fortls --help
  requires:
    - pip

about:
  home: https://github.com/gnikit/fortls
  summary: fortls - Fortran Language Server
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gnikit
