{% set name = "fortls" %}
{% set version = "2.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fortls-{{ version }}.tar.gz
  sha256: c2099161bdea89500e6f64588054609999049dd12dcd8b631f1858be81c60b9c

build:
  skip: true  # [py<37]
  entry_points:
    - fortls = fortls.__init__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - importlib-metadata  # [py<38]
    - python
    - typing-extensions  # [py<38]
    - packaging

test:
  imports:
    - fortls
  commands:
    - pip check
    - fortls --help
  requires:
    - pip

about:
  home: https://github.com/gnikit/fortls
  summary: fortls - Fortran Language Server
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gnikit
